### ISSUE TITLE
Googlable name

### ISSUE THREAD

**Issue by vgrichina** [visionmedia/uikit#22]
I think it would be good idea to make more googlable name, because now it would most often be confused with https://developer.apple.com/library/ios/#documentation/uikit/reference/UIKit_Framework/_index.html

**Comment by tj** [comment]
oh lame haha, that's what I get for not using apple tech I guess. for now i'll just make sure to mention js/jquery more so it shows up in google since i imagine most people will use "uikit js" just like they do "express js"
