### ISSUE TITLE
UI.JS unavailable on home page

### ISSUE THREAD

**Issue by svieira** [visionmedia/uikit#31]
Hitting http://visionmedia.github.com/uikit/ results in the following two errors:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://visionmedia.github.com/uikit/.build/ui.js
> 
> Uncaught ReferenceError: ui is not defined

**Comment by tj** [comment]
haha doh, I had `.build/ui.js` instead of `build/ui.js`
