### ISSUE TITLE
Notification effects do not work with Bootstrap

### ISSUE THREAD

**Issue by powmedia** [visionmedia/uikit#33]
I'm using UIKit for notifications, and I'm also using Twitter Bootstrap (v2.0).

I can get notifications to appear, but none of the effect animations work.  If I remove Bootstrap from the page, then the animations work. Haven't been able to figure out why this is yet.

**Comment by tj** [comment]
oh interesting, maybe they use those class names as well? if you find out comment on #25

**Comment by powmedia** [comment]
I was thinking that must be the problem so I tried renaming the CSS classes for .notification.slide to .notification.ui-slide and then calling `ui.notify(msg).effect('ui-slide') but there was no change.  If it was a CSS class name clash shouldn't that have sorted it?

**Comment by tj** [comment]
hmm yeah I would think so unless they're using `.notification` as well

**Comment by j2deme** [comment]
I know this issue is already closed, but...

Is there a way to make UIKit work along with Twitter Bootstrap?
