### ISSUE TITLE
escape & confirmation

### ISSUE THREAD

**Issue by pgherveou** [visionmedia/uikit#49]
nothing is triggered when a user click escape on an "escapable" confirmation dialog
Should we emit something on escape and call the callback ?

**Comment by pgherveou** [comment]
I suggest either to emit an escape event or  emit a close event upon escape
what do you think ?

**Comment by tj** [comment]
perhaps both, it should fire "close" as if they hit close, that's definitely what I would expect at least

**Comment by pgherveou** [comment]
so something like this, do you want me to create a pull request ?

``` javascript
  Dialog.prototype.escapable = function(){
    var self = this;
    $(document).bind('keydown.dialog', function(e){
      if (27 != e.which) return;
      $(this).unbind('keydown.dialog');
      self.emit('escape');
      self.emit('close');
      self.hide();
    });
  };
```

**Comment by tj** [comment]
sure!

**Comment by pgherveou** [comment]
#pull 50
