### ISSUE TITLE
Integrate with non-node project

### ISSUE THREAD

**Issue by bertomartin** [visionmedia/uikit#60]
Hi, this isn't a bug, but just a question. Not sure if I'm posting the right place. However, do you have an example of how to integrate this with a non-node project...such as a sinatra app?

Thank you.

**Comment by tj** [comment]
just include the ./build files in your app, however I would recommend using components now github.com/component/component they've replaced uikit in a more modular way

**Comment by bertomartin** [comment]
Great. Thank you sir!
